// web-next/src/app/chat/[id]/page.tsx
'use client'

import { use, useEffect, useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { useChat } from '@ai-sdk/react'
import { Chat as ChatClass } from '@ai-sdk/react'
import { DefaultChatTransport } from 'ai'
import type { UIMessage } from 'ai'
import { Check, Copy, RotateCw, ThumbsDown, ThumbsUp } from 'lucide-react'
import { ChatMessage } from '@/components/chat/message'
import { Composer } from '@/components/chat/composer'
import { ModelMenu } from '@/components/chat/model-menu'
import { ChatSidebar } from '@/components/chat/chat-sidebar'
import { useChatAttachments } from '@/hooks/use-attachments'
import { getChat, refreshChats, updateChatMessages, updateChatVotes, type LocalVote } from '@/lib/chats-store'
import { modelsStore } from '@/lib/models-store'
import { csrfHeaderName, getCsrfToken } from '@/lib/csrf'
import { toast } from '@/lib/toast'

function getMessageText(message: UIMessage) {
  return message.parts
    .filter(part => part.type === 'text')
    .map(part => ('text' in part ? part.text : ''))
    .join('')
}

export default function ChatPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const data = useMemo(() => getChat(id), [id])

  if (!data) {
    return (
      <div className="flex flex-1 flex-col items-center justify-center gap-4 text-center">
        <h1 className="text-2xl font-bold">对话不存在</h1>
        <Link href="/" className="glass-btn px-5 py-2 text-sm font-semibold">返回首页</Link>
      </div>
    )
  }

  return <ChatView data={data} />
}

function ChatView({ data }: { data: NonNullable<ReturnType<typeof getChat>> }) {
  const [input, setInput] = useState('')
  const [votes, setVotes] = useState<LocalVote[]>(data.votes ?? [])
  const [copiedId, setCopiedId] = useState('')
  const bottomRef = useRef<HTMLDivElement>(null)
  const { attachments, addFiles, removeAttachment, clearAttachments, validateAttachments, toMessageParts } = useChatAttachments()
  const { model } = modelsStore.useStore()

  // Chat 实例仅创建一次（惰性 state 初始化）；apiKey/model/effort 提交时从 store 现取
  const [chat] = useState(() =>
    new ChatClass<UIMessage>({
      id: data.id,
      messages: data.messages || [],
      transport: new DefaultChatTransport({
        api: `/api/chats/${data.id}`,
        headers: () => ({ [csrfHeaderName]: getCsrfToken() }),
        prepareSendMessagesRequest({ body, id: chatId, messageId, messages, trigger }) {
          const state = modelsStore.get()
          return {
            body: {
              ...body,
              id: chatId,
              messageId,
              messages,
              trigger,
              apiKey: state.apiKey,
              model: state.model,
              reasoningEffort: state.reasoningEffort
            }
          }
        }
      }),
      onFinish: ({ messages }) => {
        updateChatMessages(data.id, messages)
        refreshChats()
      },
      onError: (error) => {
        let message = error.message
        try {
          message = JSON.parse(message).message ?? message
        } catch { /* not JSON */ }
        toast({ description: message, color: 'error', duration: 0 })
      }
    })
  )

  const { messages, sendMessage, regenerate, stop, status } = useChat<UIMessage>({ chat })

  const autoStarted = useRef(false)
  useEffect(() => {
    if (!autoStarted.current && data.isOwner && data.messages?.length === 1) {
      autoStarted.current = true
      void regenerate().catch(() => {})
    }
  }, [data, regenerate])

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const canSubmit = input.trim().length > 0 || attachments.length > 0

  function persist(next?: UIMessage[]) {
    updateChatMessages(data.id, next ?? chat.messages)
    refreshChats()
  }

  async function onSubmit() {
    const text = input.trim()
    if (!text && !attachments.length) return
    if (attachments.length && !validateAttachments(model)) return

    try {
      const attachmentParts = attachments.length ? await toMessageParts() : []
      const request = attachmentParts.length
        ? sendMessage({ parts: [...(text ? [{ type: 'text' as const, text }] : []), ...attachmentParts] })
        : sendMessage({ text })
      persist()
      void request.catch(() => persist())
      setInput('')
      clearAttachments()
    } catch (error) {
      toast({ description: error instanceof Error ? error.message : '附件读取失败', color: 'error' })
    }
  }

  function getVote(messageId: string) {
    const vote = votes.find(item => item.messageId === messageId)
    return vote ? !!vote.isUpvoted : null
  }

  function onVote(message: UIMessage, isUpvoted: boolean) {
    const toggling = getVote(message.id) === isUpvoted
    const next = toggling
      ? votes.filter(item => item.messageId !== message.id)
      : [...votes.filter(item => item.messageId !== message.id), { chatId: data.id, messageId: message.id, isUpvoted }]
    setVotes(next)
    updateChatVotes(data.id, next)
  }

  function onCopy(message: UIMessage) {
    void navigator.clipboard.writeText(getMessageText(message))
    setCopiedId(message.id)
    setTimeout(() => setCopiedId(''), 2000)
  }

  function onRegenerate(message: UIMessage) {
    const request = regenerate({ messageId: message.id })
    persist()
    void request.catch(() => persist())
  }

  const streaming = status === 'streaming' || status === 'submitted'

  return (
    <div className="flex min-h-0 flex-1">
      <ChatSidebar />
      <div className="glass-panel glass-panel--lg aurora-shell mx-4 mb-4 flex min-w-0 flex-1 flex-col lg:ml-0">
        <div className="flex justify-start p-4">
          <ModelMenu />
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto px-4 sm:px-8">
          <div className="mx-auto flex max-w-3xl flex-col gap-6 pb-6">
            {messages.map((message) => {
              const isLast = message.id === messages[messages.length - 1]?.id
              const isStreamingThis = streaming && isLast
              return (
                <div key={message.id} className="group/message">
                  <ChatMessage message={message} />
                  {message.role === 'assistant' && !isStreamingThis && (
                    <div className="mt-1 flex gap-1 opacity-0 transition group-hover/message:opacity-100">
                      <button type="button" aria-label="复制回答" className="glass-pill p-1.5" onClick={() => onCopy(message)}>
                        {copiedId === message.id ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
                      </button>
                      <button
                        type="button"
                        aria-label="回答不错"
                        data-selected={getVote(message.id) === true}
                        className="glass-pill p-1.5"
                        onClick={() => onVote(message, true)}
                      >
                        <ThumbsUp className="size-3.5" />
                      </button>
                      <button
                        type="button"
                        aria-label="回答欠佳"
                        data-selected={getVote(message.id) === false}
                        className="glass-pill p-1.5"
                        onClick={() => onVote(message, false)}
                      >
                        <ThumbsDown className="size-3.5" />
                      </button>
                      <button type="button" aria-label="重新生成" className="glass-pill p-1.5" onClick={() => onRegenerate(message)}>
                        <RotateCw className="size-3.5" />
                      </button>
                    </div>
                  )}
                </div>
              )
            })}
            {streaming && messages[messages.length - 1]?.role === 'user' && (
              <p className="label-mono animate-pulse">思考中...</p>
            )}
            <div ref={bottomRef} />
          </div>
        </div>

        <div className="p-4">
          <div className="mx-auto max-w-3xl">
            <Composer
              value={input}
              onChange={setInput}
              onSubmit={() => { void onSubmit() }}
              onStop={() => { void stop() }}
              status={status}
              attachments={attachments}
              onPickFiles={files => addFiles(files, model)}
              onRemoveAttachment={removeAttachment}
              canSubmit={canSubmit}
            />
          </div>
        </div>
      </div>
    </div>
  )
}

// src/pages/chat/[id].vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { Chat } from '@ai-sdk/vue'
import { DefaultChatTransport } from 'ai'
import type { UIMessage } from 'ai'
import { useModels } from '../../composables/useModels'
import { useChats, type LocalVote } from '../../composables/useChats'
import { useCsrf } from '../../composables/useCsrf'
import { useRoute } from 'vue-router'
import ChatMessageContent from '../../components/chat/message/MessageContent.vue'
import ChatMessageActions from '../../components/chat/message/MessageActions.vue'
import ChatIndicator from '../../components/chat/Indicator.vue'
import ChatComposer from '../../components/chat/ChatComposer.vue'
import Navbar from '../../components/Navbar.vue'
import PromptPresetRow from '../../components/PromptPresetRow.vue'
import { chatFollowupPresets } from '../../data/promptPresets'
import { useChatAttachments } from '../../composables/useChatAttachments'

const route = useRoute<'/chat/[id]'>()
const toast = useToast()
const { apiKey, model, reasoningEffort } = useModels()
const { fetchChats, getChat, updateChatMessages, updateChatVotes } = useChats()
const { csrf, headerName } = useCsrf()

const data = ref(getChat(route.params.id as string))

const isOwner = computed(() => data.value?.isOwner ?? false)

const votes = ref<LocalVote[]>(data.value?.votes ?? [])

const input = ref('')
const attachmentPending = ref(false)
const {
  attachments,
  hasAttachments,
  addFiles,
  removeAttachment,
  clearAttachments,
  validateAttachments,
  toMessageParts
} = useChatAttachments()

const chat = new Chat({
  id: data.value?.id,
  messages: data.value?.messages || [],
  transport: new DefaultChatTransport({
    api: `/api/chats/${data.value?.id}`,
    headers: { [headerName]: csrf() },
    prepareSendMessagesRequest({ body, id, messageId, messages, trigger }) {
      return {
        body: {
          ...body,
          id,
          messageId,
          messages,
          trigger,
          apiKey: apiKey.value,
          model: model.value,
          reasoningEffort: reasoningEffort.value
        }
      }
    }
  }),
  onData: (dataPart) => {
    if (dataPart.type === 'data-chat-title') {
      void fetchChats()
    }
  },
  onFinish({ messages }) {
    persistMessages(messages)
  },
  onError(error) {
    let message = error.message
    if (typeof message === 'string') {
      try { message = JSON.parse(message).message ?? message } catch { /* not JSON */ }
    }
    toast.add({
      description: message,
      icon: 'i-lucide-alert-circle',
      color: 'error',
      duration: 0
    })
  }
})

const canSendMessage = computed(() => input.value.trim().length > 0 || hasAttachments.value)

function persistMessages(messages = chat.messages) {
  if (!data.value?.id) return

  updateChatMessages(data.value.id, messages)
  data.value = getChat(data.value.id)
  void fetchChats()
}

function onAttachmentFiles(files: File[]) {
  addFiles(files, model.value)
}

function useChatPromptPreset(prompt: string) {
  if (chat.status !== 'ready') return
  input.value = prompt
}

async function handleSubmit(e?: Event) {
  e?.preventDefault()
  const text = input.value.trim()
  if (!text && !hasAttachments.value) return

  attachmentPending.value = true
  try {
    if (hasAttachments.value && !validateAttachments(model.value)) return

    const attachmentParts = hasAttachments.value ? await toMessageParts() : []
    const request = attachmentParts.length
      ? chat.sendMessage({
        parts: [
          ...(text ? [{ type: 'text' as const, text }] : []),
          ...attachmentParts
        ]
      })
      : chat.sendMessage({ text })
    persistMessages()
    void request.catch(() => persistMessages())

    input.value = ''
    clearAttachments()
  } catch (error) {
    toast.add({
      description: error instanceof Error ? error.message : '附件读取失败',
      icon: 'i-lucide-alert-circle',
      color: 'error'
    })
  } finally {
    attachmentPending.value = false
  }
}

const editingMessageId = ref<string | null>(null)

function startEdit(message: UIMessage) {
  if (editingMessageId.value) return

  editingMessageId.value = message.id
}

function cancelEdit() {
  editingMessageId.value = null
}

async function saveEdit(message: UIMessage, text: string) {
  editingMessageId.value = null
  const request = chat.sendMessage({ text, messageId: message.id })
  persistMessages()
  void request.catch(() => persistMessages())
}

async function regenerateMessage(message: UIMessage) {
  const request = chat.regenerate({ messageId: message.id })
  persistMessages()
  void request.catch(() => persistMessages())
}

function getVote(messageId: string) {
  const vote = votes.value.find(v => v.messageId === messageId)
  if (!vote) return null
  return !!vote.isUpvoted
}

async function vote(message: UIMessage, isUpvoted: boolean) {
  const toggling = getVote(message.id) === isUpvoted
  const next = toggling ? null : isUpvoted

  votes.value = next === null
    ? votes.value.filter(v => v.messageId !== message.id)
    : [
        ...votes.value.filter(v => v.messageId !== message.id),
        { chatId: data.value!.id, messageId: message.id, isUpvoted: next }
      ]

  updateChatVotes(data.value!.id, votes.value)
}

onMounted(() => {
  if (isOwner.value && data.value?.messages?.length === 1) {
    const request = chat.regenerate()
    void request.catch(() => persistMessages())
  }
})
</script>

<template>
  <UDashboardPanel
    v-if="data?.id"
    id="chat"
    class="relative min-h-0"
    :ui="{ body: 'p-0 sm:p-0 overscroll-none' }"
  >
    <template #header>
      <Navbar />
    </template>

    <template #body>
      <UContainer class="relative flex-1 flex flex-col gap-4 sm:gap-6">
        <div class="pointer-events-none absolute inset-x-10 top-8 h-24 rounded-full bg-primary/8 blur-3xl" />
        <UChatMessages
          should-auto-scroll
          :messages="chat.messages"
          :status="chat.status"
          :spacing-offset="isOwner ? 160 : 0"
          class="relative pt-(--ui-header-height) pb-4 sm:pb-6"
        >
          <template #indicator>
            <div class="flex items-center gap-1.5">
              <ChatIndicator />

              <UChatShimmer
                text="思考中..."
                class="text-sm"
              />
            </div>
          </template>

          <template #content="{ message }">
            <ChatMessageContent
              :message="message"
              :editing="isOwner && editingMessageId === message.id"
              @save="saveEdit"
              @cancel-edit="cancelEdit"
            />
          </template>

          <template
            v-if="isOwner"
            #actions="{ message }"
          >
            <div :class="message.role === 'assistant' ? 'ml-12' : undefined">
              <ChatMessageActions
                :message="message"
                :streaming="chat.status === 'streaming' && message.id === chat.messages[chat.messages.length - 1]?.id"
                :editing="editingMessageId === message.id"
                :vote="getVote(message.id)"
                @edit="startEdit"
                @regenerate="regenerateMessage"
                @vote="vote"
              />
            </div>
          </template>
        </UChatMessages>

        <div
          v-if="isOwner"
          class="sticky bottom-4 z-10 space-y-2"
        >
          <PromptPresetRow
            v-if="!attachments.length && !input.trim()"
            class="mx-auto max-w-3xl px-2"
            :presets="chatFollowupPresets"
            :disabled="chat.status !== 'ready'"
            @select="useChatPromptPreset"
          />

          <ChatComposer
            v-model="input"
            :status="chat.status"
            :error="chat.error"
            :attachments="attachments"
            :attachment-pending="attachmentPending"
            :can-submit="canSendMessage"
            @submit="handleSubmit"
            @stop="chat.stop()"
            @reload="chat.regenerate()"
            @files="onAttachmentFiles"
            @remove-attachment="removeAttachment"
          />
        </div>
      </UContainer>
    </template>
  </UDashboardPanel>

  <UContainer
    v-else
    class="flex-1 flex flex-col gap-4 sm:gap-6"
  >
    <UError
      :error="{ statusMessage: '对话不存在', statusCode: 404 }"
      class="min-h-full"
    >
      <template #links>
        <UButton
          to="/"
          size="lg"
          label="返回首页"
        />
      </template>
    </UError>
  </UContainer>
</template>
