// src/components/studio/MediaModelMenu.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useMediaModels } from '../../composables/studio/useMediaModels'

const {
  activeModel,
  activeModelLabel,
  activeModelOptions,
  loadingModels,
  selectModel
} = useMediaModels()

const activeIcon = computed(() => {
  return activeModelOptions.value.find(item => item.value === activeModel.value)?.icon || 'i-lucide-box'
})
</script>

<template>
  <UPopover>
    <UButton
      type="button"
      color="neutral"
      variant="ghost"
      size="sm"
      :icon="activeIcon"
      :label="activeModelLabel"
      trailing-icon="i-lucide-chevron-up"
      class="glass-pill max-w-48 shrink-0 rounded-full font-medium"
      :ui="{ label: 'truncate' }"
    />

    <template #content>
      <div class="glass-panel w-80 p-2">
        <p class="label-mono mb-1.5 flex items-center gap-1.5 px-1.5 pt-1">
          选择模型
          <UIcon
            v-if="loadingModels"
            name="i-lucide-loader-circle"
            class="size-3 animate-spin"
          />
        </p>
        <div class="flex max-h-80 flex-col gap-1 overflow-y-auto">
          <button
            v-for="item in activeModelOptions"
            :key="item.value"
            type="button"
            class="glass-pill flex w-full items-start gap-2.5 rounded-xl px-2.5 py-2 text-left"
            :data-selected="activeModel === item.value"
            @click="selectModel(item.value)"
          >
            <UIcon
              :name="item.icon"
              class="mt-0.5 size-4 shrink-0"
            />
            <span class="min-w-0 flex-1">
              <span class="flex items-center justify-between gap-2">
                <span class="truncate text-sm font-semibold">{{ item.label }}</span>
                <span
                  v-if="item.price"
                  class="label-mono shrink-0 text-[10px]"
                >{{ item.price }}</span>
              </span>
              <span
                v-if="item.description"
                class="mt-0.5 block text-xs leading-4 opacity-70"
              >{{ item.description }}</span>
            </span>
            <UIcon
              v-if="activeModel === item.value"
              name="i-lucide-check"
              class="mt-0.5 size-4 shrink-0"
            />
          </button>
        </div>
      </div>
    </template>
  </UPopover>
</template>

// web-next/src/components/studio/media-model-menu.tsx
'use client'

import { useState } from 'react'
import { Popover } from '@heroui/react'
import { Check, ChevronUp, LoaderCircle, Sparkles, Zap } from 'lucide-react'
import {
  activeMediaModel,
  curatedMediaOptions,
  mediaModelsStore,
  selectMediaModel
} from '@/lib/studio/media-models-store'
import { resolveMediaModelSpec } from '@/lib/shared/media-models'

/** lucide 没有品牌图标，按 provider 映射（grok → Zap，openai → Sparkles） */
const providerIcons: Record<'openai' | 'grok', typeof Sparkles> = {
  openai: Sparkles,
  grok: Zap
}

/** 创作台模型菜单（含价格 / 说明，向上弹出） */
export function MediaModelMenu() {
  const state = mediaModelsStore.useStore()
  const [open, setOpen] = useState(false)

  const options = curatedMediaOptions(state, state.mediaMode)
  const active = activeMediaModel(state)
  const activeLabel = options.find(item => item.value === active)?.label || resolveMediaModelSpec(active).label
  const ActiveIcon = providerIcons[resolveMediaModelSpec(active).provider]

  return (
    <Popover.Root isOpen={open} onOpenChange={setOpen}>
      <Popover.Trigger className="glass-pill flex h-8 max-w-48 shrink-0 cursor-pointer items-center gap-1.5 px-2.5 text-sm font-medium">
        <ActiveIcon className="size-4 shrink-0" />
        <span className="truncate">{activeLabel}</span>
        <ChevronUp className="size-4 shrink-0 opacity-60" />
      </Popover.Trigger>

      <Popover.Content placement="top start" offset={8} className="glass-panel w-80">
        <Popover.Dialog className="p-2 outline-none">
          <p className="label-mono mb-1.5 flex items-center gap-1.5 px-1.5 pt-1">
            选择模型
            {state.loadingModels && <LoaderCircle className="size-3 animate-spin" />}
          </p>
          <div className="flex max-h-80 flex-col gap-1 overflow-y-auto">
            {options.map((item) => {
              const ItemIcon = providerIcons[item.provider]
              return (
                <button
                  key={item.value}
                  type="button"
                  data-selected={active === item.value}
                  className="glass-pill flex w-full items-start gap-2.5 rounded-xl px-2.5 py-2 text-left"
                  onClick={() => selectMediaModel(item.value)}
                >
                  <ItemIcon className="mt-0.5 size-4 shrink-0" />
                  <span className="min-w-0 flex-1">
                    <span className="flex items-center justify-between gap-2">
                      <span className="truncate text-sm font-semibold">{item.label}</span>
                      {item.price && <span className="label-mono shrink-0 text-[10px]">{item.price}</span>}
                    </span>
                    {item.description && (
                      <span className="mt-0.5 block text-xs leading-4 opacity-70">{item.description}</span>
                    )}
                  </span>
                  {active === item.value && <Check className="mt-0.5 size-4 shrink-0" />}
                </button>
              )
            })}
          </div>
        </Popover.Dialog>
      </Popover.Content>
    </Popover.Root>
  )
}
