// src/components/TopNav.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()

const isStudioRoute = computed(() => route.path.startsWith('/images') || route.path.startsWith('/studio'))
const isGalleryRoute = computed(() => route.path.startsWith('/gallery'))

const tabs = computed(() => [
  { label: '对话', icon: 'i-lucide-message-circle', to: '/', selected: !isStudioRoute.value && !isGalleryRoute.value },
  { label: '创作台', icon: 'i-lucide-wand-sparkles', to: '/studio', selected: isStudioRoute.value },
  { label: '灵感', icon: 'i-lucide-lightbulb', to: '/gallery', selected: isGalleryRoute.value }
])
</script>

<template>
  <div class="pointer-events-none fixed left-4 top-3 z-50">
    <ULink
      to="/"
      class="glass-chip pointer-events-auto inline-flex items-center gap-2 py-1.5 pl-1.5 pr-3 transition-transform hover:-translate-y-0.5"
    >
      <img
        src="/logo-mark.jpg"
        alt="pigcoder"
        class="size-7 shrink-0 rounded-full object-cover ring-2 ring-white/70 dark:ring-white/10"
      >
      <span class="hidden text-sm font-bold tracking-tight text-highlighted sm:inline">pigcoder</span>
    </ULink>
  </div>

  <nav class="pointer-events-none fixed top-3 left-1/2 z-50 -translate-x-1/2">
    <div class="glass-chip pointer-events-auto inline-flex items-center gap-1 p-1">
      <ULink
        v-for="tab in tabs"
        :key="tab.to"
        :to="tab.to"
        class="glass-pill inline-flex h-8 items-center gap-1.5 px-3.5 text-sm font-semibold"
        :data-selected="tab.selected"
      >
        <UIcon
          :name="tab.icon"
          class="size-4"
        />
        <span class="whitespace-nowrap">{{ tab.label }}</span>
      </ULink>
    </div>
  </nav>

  <div class="pointer-events-none fixed right-4 top-3 z-50">
    <UColorModeButton
      color="neutral"
      variant="ghost"
      class="glass-chip pointer-events-auto"
    />
  </div>
</template>

// web-next/src/components/top-nav.tsx
'use client'

import Link from 'next/link'
import Image from 'next/image'
import { usePathname } from 'next/navigation'
import { useCallback, useState } from 'react'

const tabs = [
  { label: '对话', href: '/', icon: '💬' },
  { label: '创作台', href: '/studio', icon: '✨' },
  { label: '灵感', href: '/gallery', icon: '💡' }
] as const

function isTabActive(pathname: string, href: string) {
  if (href === '/') {
    return !pathname.startsWith('/studio') && !pathname.startsWith('/gallery')
  }
  return pathname.startsWith(href)
}

function ColorModeButton() {
  // 惰性读取 DOM 初始主题；SSR 时为 false，配合 suppressHydrationWarning 消除水合差异
  const [dark, setDark] = useState(() =>
    typeof document !== 'undefined' && document.documentElement.classList.contains('dark')
  )

  const toggle = useCallback(() => {
    const next = !document.documentElement.classList.contains('dark')
    document.documentElement.classList.toggle('dark', next)
    localStorage.setItem('color-scheme', next ? 'dark' : 'light')
    setDark(next)
  }, [])

  return (
    <button
      type="button"
      aria-label="切换深浅色"
      className="glass-chip pointer-events-auto flex size-9 items-center justify-center"
      suppressHydrationWarning
      onClick={toggle}
    >
      {dark ? '🌙' : '☀️'}
    </button>
  )
}

export function TopNav() {
  const pathname = usePathname()

  return (
    <>
      <div className="pointer-events-none fixed left-4 top-3 z-50">
        <Link
          href="/"
          className="glass-chip pointer-events-auto inline-flex items-center gap-2 py-1.5 pl-1.5 pr-3 transition-transform hover:-translate-y-0.5"
        >
          <Image
            src="/logo-mark.jpg"
            alt="pigcoder"
            width={28}
            height={28}
            className="size-7 shrink-0 rounded-full object-cover"
          />
          <span className="hidden text-sm font-bold tracking-tight sm:inline">pigcoder</span>
        </Link>
      </div>

      <nav className="pointer-events-none fixed left-1/2 top-3 z-50 -translate-x-1/2">
        <div className="glass-chip pointer-events-auto inline-flex items-center gap-1 p-1">
          {tabs.map(tab => (
            <Link
              key={tab.href}
              href={tab.href}
              data-selected={isTabActive(pathname, tab.href)}
              className="glass-pill inline-flex h-8 items-center gap-1.5 px-3.5 text-sm font-semibold"
            >
              <span className="whitespace-nowrap">{tab.label}</span>
            </Link>
          ))}
        </div>
      </nav>

      <div className="pointer-events-none fixed right-4 top-3 z-50">
        <ColorModeButton />
      </div>
    </>
  )
}
