// web-next/src/components/studio/task-batch-toolbar.tsx
'use client'

import { CheckCheck, Download, SquareCheck, Trash, X } from 'lucide-react'
import {
  deleteSelectedTasks,
  downloadSelectedTasks,
  selectAllBatchTasks,
  selectDownloadableTasks,
  selectSelectedBatchTasks,
  studioStore,
  toggleBatchMode
} from '@/lib/studio/tasks-store'

const pillClass = 'glass-pill flex items-center gap-1 px-2.5 py-1 text-xs font-semibold disabled:cursor-not-allowed disabled:opacity-40'

/** 批量管理工具栏：全选 / 下载 / 删除所选 / 退出 */
export function TaskBatchToolbar() {
  const state = studioStore.useStore()
  const selectedBatchTasks = selectSelectedBatchTasks(state)
  const downloadableTasks = selectDownloadableTasks(state)

  return (
    <div className="flex flex-wrap items-center gap-1.5">
      {state.batchMode
        ? (
            <>
              <span className="label-mono mr-1">
                已选 {selectedBatchTasks.length} / {downloadableTasks.length}
              </span>
              <button type="button" className={pillClass} onClick={() => selectAllBatchTasks()}>
                <CheckCheck className="size-3.5" />
                全选
              </button>
              <button
                type="button"
                disabled={!selectedBatchTasks.length}
                className={pillClass}
                onClick={() => downloadSelectedTasks()}
              >
                <Download className="size-3.5" />
                下载
              </button>
              <button
                type="button"
                disabled={!selectedBatchTasks.length}
                className={`${pillClass} text-red-500 hover:text-red-600`}
                onClick={() => { void deleteSelectedTasks() }}
              >
                <Trash className="size-3.5" />
                删除
              </button>
              <button type="button" className={pillClass} onClick={() => toggleBatchMode()}>
                <X className="size-3.5" />
                取消
              </button>
            </>
          )
        : (
            <button
              type="button"
              disabled={!downloadableTasks.length}
              className={pillClass}
              onClick={() => toggleBatchMode()}
            >
              <SquareCheck className="size-3.5" />
              批量管理
            </button>
          )}
    </div>
  )
}

// src/components/studio/TaskBatchToolbar.vue
<script setup lang="ts">
import { useStudioTasks } from '../../composables/studio/useStudioTasks'

const tasks = useStudioTasks()
const { batchMode, selectedBatchTasks, downloadableTasks } = tasks
</script>

<template>
  <div class="flex flex-wrap items-center gap-1.5">
    <template v-if="batchMode">
      <span class="label-mono mr-1">
        已选 {{ selectedBatchTasks.length }} / {{ downloadableTasks.length }}
      </span>
      <UButton
        type="button"
        icon="i-lucide-check-check"
        label="全选"
        color="neutral"
        variant="ghost"
        size="xs"
        class="glass-pill rounded-full"
        @click="tasks.selectAllBatchTasks()"
      />
      <UButton
        type="button"
        icon="i-lucide-download"
        label="下载"
        color="neutral"
        variant="ghost"
        size="xs"
        class="glass-pill rounded-full"
        :disabled="!selectedBatchTasks.length"
        @click="tasks.downloadSelectedTasks()"
      />
      <UButton
        type="button"
        icon="i-lucide-trash"
        label="删除"
        color="error"
        variant="ghost"
        size="xs"
        class="glass-pill rounded-full"
        :disabled="!selectedBatchTasks.length"
        @click="tasks.deleteSelectedTasks()"
      />
      <UButton
        type="button"
        icon="i-lucide-x"
        label="取消"
        color="neutral"
        variant="ghost"
        size="xs"
        class="glass-pill rounded-full"
        @click="tasks.toggleBatchMode()"
      />
    </template>
    <UButton
      v-else
      type="button"
      icon="i-lucide-square-check"
      label="批量管理"
      color="neutral"
      variant="ghost"
      size="xs"
      class="glass-pill rounded-full"
      :disabled="!downloadableTasks.length"
      @click="tasks.toggleBatchMode()"
    />
  </div>
</template>
